### ISSUE TITLE
frutool assumes "true" for section if "include" option is missing  

### ISSUE THREAD

**Issue by MichaelLettrich** [genotrance/fru-tool#21]
**Version:** 4.0.1 (pip)

**Problem:**
In the `common` section, there are options to control which sections are included in the FRU file, starting with `include_`. If one of those `include_` statements is removed, the tool assumes the removed `include` statement is "true". As a result, the header of the fru binary contains offsets to those FRU-sections, and blank FRU sections are inserted at those fields. This results in an invalid FRU. 

**Reproducer:**
The issue can be reproduced with the following `toml` configuration.

```toml
[common]
format_version = 1
size = 256 
include_board = true

[board]
format_version = 1
language_code = 0

mfg_date_time = "2024-01-01 01:01"
manufacturer = "Test Factory .Inc"
product_name = "Test Board"
serial_number = "01234"
part_number = "5678"
fru_file_id = "1"
custom_fields = ["", ""]
```

I did not do any in-depth investigation in the source-code, but if you would like me to help with the fix, let me know.
